### ISSUE TITLE
panic

### ISSUE THREAD

**Issue by wfdoran** [shuban-789/bluefox#5]
Running demo code results in panic.

```

.../bluefox/src> ./bluefox -c 127.0.0.1 1234
panic: runtime error: index out of range [4] with length 4

goroutine 1 [running]:
main.main()
	.../bluefox/src/bluefox.go:272 +0x592

```

**Comment by shuban-789** [comment]
Hi there. It seems the computation which checks for `os.Args[4]` is happening even when `os.Args` does not have the payload option. The issue was I did not increase it to the correct os.Args value and used an `&&`. 

In my new fix I nested the `strings.Compare` and stated os.Args must be greater than 4 to accomodate the payload.

![image](https://github.com/user-attachments/assets/911a2f19-2cce-4e47-99dc-66c4f1041334)

This should work now. Thank you for your insights and let me know if you catch any other errors with my code. It seems I did not catch this one as I was too busy implementing the payload feature.
